### ISSUE TITLE
[Error 500] GET prices/usd when rabbitmq is down

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1003]
**Describe the bug**
Some 500 error are appearing in the logs when GET price/usd happen in the moment that rabbitmq is not responding for unknown reason. 

**To Reproduce**
1. Clean readis cache and turn off rabbitmq container
2. Then GET some token /prices/usd
3. Inmediatly we get a 500 error

**Expected behavior**
I think that should catch the exception and don't delay the task to get the price and return the current price without 500 error. 
**Exception traceback**
```
2022-08-03 13:42:50,833 [ERROR] [MainProcess] Internal Server Error: /api/v1/tokens/0x0AaE289A554cB3C97b3121db837eD9ce8635367F/prices/usd/
Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 30, in __call__    return self.__value__AttributeError: 'ChannelPromise' object has no attribute '__value__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors    yield  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 433, in _ensure_connection    return retry_over_time(  File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 312, in retry_over_time    return fun(*args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 877, in _connection_factory    self._connection = self._establish_connection()  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 812, in _establish_connection    conn = self.transport.establish_connection()  File "/usr/local/lib/python3.10/site-packages/kombu/transport/pyamqp.py", line 201, in establish_connection    conn.connect()  File "/usr/local/lib/python3.10/site-packages/amqp/connection.py", line 323, in connect    self.transport.connect()  File "/usr/local/lib/python3.10/site-packages/amqp/transport.py", line 129, in connect    self._connect(self.host, self.port, self.connect_timeout)  File "/usr/local/lib/python3.10/site-packages/amqp/transport.py", line 184, in _connect    self.sock.connect(sa)  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 607, in connect    raise _SocketError(err, strerror(err))ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner    response = get_response(request)  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response    response = wrapped_callback(request, *callback_args, **callback_kwargs)  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view    return view_func(*args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view    return self.dispatch(request, *args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch    response = self.handle_exception(exc)  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception    self.raise_uncaught_exception(exc)  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception    raise exc  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch    response = handler(request, *args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper    return bound_method(*args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 133, in _wrapped_view    response = view_func(request, *args, **kwargs)  File "/app/safe_transaction_service/tokens/views.py", line 92, in get    fiat_price_with_timestamp = next(  File "/app/safe_transaction_service/tokens/services/price_service.py", line 347, in get_cached_usd_values    for token_eth_values_with_timestamp in self.get_cached_token_eth_values(  File "/app/safe_transaction_service/tokens/services/price_service.py", line 324, in get_cached_token_eth_values    task_result = calculate_token_eth_price_task.delay(  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 425, in delay    return self.apply_async(args, kwargs)  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 575, in apply_async    return app.send_task(  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 788, in send_task    amqp.send_task_message(P, name, message, **options)  File "/usr/local/lib/python3.10/site-packages/celery/app/amqp.py", line 510, in send_task_message    ret = producer.publish(  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 177, in publish    return _publish(  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 523, in _ensured    return fun(*args, **kwargs)  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 186, in _publish    channel = self.channel  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 209, in _get_channel    channel = self._channel = channel()  File "/usr/local/lib/python3.10/site-packages/kombu/utils/functional.py", line 32, in __call__    value = self.__value__ = self.__contract__()  File "/usr/local/lib/python3.10/site-packages/kombu/messaging.py", line 225, in <lambda>    channel = ChannelPromise(lambda: connection.default_channel)  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 895, in default_channel    self._ensure_connection(**conn_opts)  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 432, in _ensure_connection    with ctx():  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__    self.gen.throw(typ, value, traceback)  File "/usr/local/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors    raise ConnectionError(str(exc)) from exckombu.exceptions.OperationalError: [Errno 111] Connection refused
```

**Comment by Uxio0** [comment]
Could you attach the traceback for the exception?

**Comment by moisses89** [comment]
> Could you attach the traceback for the exception?

Added

**Comment by Uxio0** [comment]
Well, that's expected if we set down rabbitmq. We shouldn't `try catch` calls that involves rabbitmq, same as we don't `try catch` every call to `redis` or `postgres`. 

Although we should try to fix `rabbitmq` if we see downtimes

**Comment by moisses89** [comment]
Maybe is because I'm not understanding why we run an async task for this GET endpoint.
The strange thing is that if the task created fail (rabbitmq up) the endpoint then return 200 and result:
```
safe_transaction_service.tokens.tasks.calculate_token_eth_price_task:

ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f19f86b8dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))")) 
```

**Comment by moisses89** [comment]
This is the description of the function that call delay for the price_calculation. 
```
Get token eth prices with timestamp of calculation if ready on cache. If not, schedule tasks to do
the calculation so next time is available on cache and return `0.` and current datetime
```
Then following this if the task couldn't be created should return 0? what do you think?

**Comment by Uxio0** [comment]
No, if the task couldn't be created something is really off in our infra, similar af if something in database cannot be created

**Comment by moisses89** [comment]
Then 500 for this case is correct. 
Closing the issue.
