### ISSUE TITLE
ModuleNotFoundError: No module named 'django_extensions'

### ISSUE THREAD

**Issue by benjamintshi** [safe-global/safe-transaction-service#1028]
i follow Setup for development , but after run docker show this error.

```
==> 08:51:30 ==> Collecting statics... 
==> 08:51:30 ==> Send via Slack info about service version and network
==> 08:51:30 ==> Running Gunicorn... 
[2022-08-18 08:51:30 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2022-08-18 08:51:30 +0000] [1] [INFO] Listening at: unix:/nginx/gunicorn.socket,http://0.0.0.0:8888 (1)
[2022-08-18 08:51:30 +0000] [1] [INFO] Using worker: gevent
[2022-08-18 08:51:30 +0000] [13] [INFO] Booting worker with pid: 13
[2022-08-18 08:51:30 +0000] [13] [INFO] Making Psycopg2 Green
[2022-08-18 08:51:30 +0000] [13] [INFO] Made Psycopg2 Green
Traceback (most recent call last):
  File "/app/manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'
[2022-08-18 08:51:31 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/wsgi.py", line 38, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.10/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_extensions'
[2022-08-18 08:51:31 +0000] [13] [INFO] Worker exiting (pid: 13)
[2022-08-18 08:51:31 +0000] [1] [INFO] Shutting down: Master
[2022-08-18 08:51:31 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by benjamintshi** [comment]
```
 1057  source venv/bin/activate
 1058  pip3 install -r requirements-dev.txt
 1059  pre-commit install -f
 1060  ./run_tests.sh
 1061  docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
```

**Comment by benjamintshi** [comment]
![image](https://user-images.githubusercontent.com/6221737/185434520-0a809e70-8021-40c9-8939-68cad4020d44.png)

**Comment by moisses89** [comment]
Ok.
For now, you can remove in `config/settings/local.py` `django_extensions`
I mean change this line `INSTALLED_APPS += ["debug_toolbar", "django_extensions"]` 
For this `INSTALLED_APPS += ["debug_toolbar"]` 
Remember rebuild web: 
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml build web` 

This is a temporary solution if docker is for development then I think that should install also `requirements.dev.txt`

**Comment by benjamintshi** [comment]
@moisses89 thank you so much. it works.

**Comment by moisses89** [comment]
@Uxio0 we should take a look to this, basically the issue is that docker is not installing `requirements.dev.txt` but is using local configuration that includes `django_extensions` should we create separate dockerfile for dev and other for prod?

**Comment by Uxio0** [comment]
No, not at all. I think we should include `django-extensions` on `requirements.txt`, as the extensions are so useful even for our production environments
