### ISSUE TITLE
You can't write against a read only replica.

### ISSUE THREAD

**Issue by steliyannedev** [safe-global/safe-transaction-service#1252]
**Describe the bug**
Started experience this issue last week, before this the service was working just fine, by the looks of it, its trying to create a replica and write in it but the replica is a read only

**To Reproduce**
unknown, happens randomly or when trying to execute a certain task

**Environment (please complete the following information):**
 - Staging or production?
 - Which chain?
 - OS: linux
 - Version forked repo, 65 commit behind

```
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:47.159 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:47.159 * Connecting to MASTER 185.246.90.205:8886
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:47.159 * MASTER <-> REPLICA sync started
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:47.159 * REPLICAOF 185.246.90.205:8886 enabled (user request from 'id=6 addr=109.237.96.124:42386 laddr=172.20.0.4:6379 fd=12 name= age=1 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=48 qbuf-free=20426 argv-mem=25 multi-mem=0 rbs=1024 rbp=5 obl=0 oll=0 omem=0 tot-mem=22321 events=r cmd=slaveof user=default redir=-1 resp=2')
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:48.618 * Non blocking connect for SYNC fired the event.
safe-transaction-service-scheduler-1                      | 2023-01-05 08:40:48,735 [INFO] [???/???] Scheduler: Sending due task Index Safe events (L2) (safe_transaction_service.history.tasks.index_safe_events_task)
safe-transaction-service-indexer-worker-1                 | 2023-01-05 08:40:48,759 [ERROR] [8d3199f2/index_safe_events_task] Task safe_transaction_service.history.tasks.index_safe_events_task[8d3199f2-6e91-41d0-a008-1521433c5e3f] raised unexpected: ReadOnlyError("You can't write against a read only replica.")
safe-transaction-service-indexer-worker-1                 | Traceback (most recent call last):
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
safe-transaction-service-indexer-worker-1                 |     R = retval = fun(*args, **kwargs)
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
safe-transaction-service-indexer-worker-1                 |     return self.run(*args, **kwargs)
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
safe-transaction-service-indexer-worker-1                 |     return task._orig_run(*args, **kwargs)
safe-transaction-service-indexer-worker-1                 |   File "/app/safe_transaction_service/history/tasks.py", line 221, in index_safe_events_task
safe-transaction-service-indexer-worker-1                 |     with only_one_running_task(self):
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
safe-transaction-service-indexer-worker-1                 |     return next(self.gen)
safe-transaction-service-indexer-worker-1                 |   File "/app/safe_transaction_service/utils/tasks.py", line 83, in only_one_running_task
safe-transaction-service-indexer-worker-1                 |     with redis.lock(
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/lock.py", line 158, in __enter__
safe-transaction-service-indexer-worker-1                 |     if self.acquire():
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/lock.py", line 207, in acquire
safe-transaction-service-indexer-worker-1                 |     if self.do_acquire(token):
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/lock.py", line 223, in do_acquire
safe-transaction-service-indexer-worker-1                 |     if self.redis.set(self.name, token, nx=True, px=timeout):
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/commands/core.py", line 2220, in set
safe-transaction-service-indexer-worker-1                 |     return self.execute_command("SET", *pieces, **options)
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1238, in execute_command
safe-transaction-service-indexer-worker-1                 |     return conn.retry.call_with_retry(
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
safe-transaction-service-indexer-worker-1                 |     return do()
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1239, in <lambda>
safe-transaction-service-indexer-worker-1                 |     lambda: self._send_command_parse_response(
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1215, in _send_command_parse_response
safe-transaction-service-indexer-worker-1                 |     return self.parse_response(conn, command_name, **options)
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1254, in parse_response
safe-transaction-service-indexer-worker-1                 |     response = connection.read_response()
safe-transaction-service-indexer-worker-1                 |   File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 839, in read_response
safe-transaction-service-indexer-worker-1                 |     raise response
safe-transaction-service-indexer-worker-1                 | redis.exceptions.ReadOnlyError: You can't write against a read only replica.
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:49.065 * Master replied to PING, replication can continue...
safe-transaction-service-db-1                             | 2023-01-05 08:40:49.165 UTC [524] FATAL:  password authentication failed for user "postgres"
safe-transaction-service-db-1                             | 2023-01-05 08:40:49.165 UTC [524] DETAIL:  Password does not match for user "postgres".
safe-transaction-service-db-1                             | 	Connection matched pg_hba.conf line 99: "host all all all md5"
safe-transaction-service-db-1                             | chattr: setting flags on /tmp/: Operation not permitted
safe-transaction-service-db-1                             | chattr: setting flags on /var/tmp/: Operation not permitted
safe-transaction-service-db-1                             | chattr: setting flags on /var/spool/cron: Operation not permitted
safe-transaction-service-db-1                             | chattr: can't open '/var/spool/cron/crontabs': Symbolic link loop
safe-transaction-service-db-1                             | chattr: can't stat '/etc/crontab': No such file or directory
safe-transaction-service-db-1                             | bash: line 8: ufw: command not found
safe-transaction-service-db-1                             | bash: line 9: iptables: command not found
safe-transaction-service-db-1                             | bash: line 11: sudo: command not found
safe-transaction-service-db-1                             | bash: line 12: /proc/sys/kernel/nmi_watchdog: Read-only file system
safe-transaction-service-db-1                             | bash: line 13: /etc/sysctl.conf: Permission denied
safe-transaction-service-db-1                             | bash: line 14: userdel: command not found
safe-transaction-service-db-1                             | bash: line 15: userdel: command not found
safe-transaction-service-db-1                             | chattr: can't stat '/root/.ssh/': Permission denied
safe-transaction-service-db-1                             | chattr: can't stat '/root/.ssh/authorized_keys': Permission denied
safe-transaction-service-db-1                             | 2023-01-05 08:40:49.726 UTC [620] FATAL:  password authentication failed for user "postgres"
safe-transaction-service-db-1                             | 2023-01-05 08:40:49.726 UTC [620] DETAIL:  Password does not match for user "postgres".
safe-transaction-service-db-1                             | 	Connection matched pg_hba.conf line 99: "host all all all md5"
safe-transaction-service-db-1                             | cat: can't open '/tmp/.X11-unix/01': No such file or directory
safe-transaction-service-db-1                             | cat: can't open '/tmp/.X11-unix/11': No such file or directory
safe-transaction-service-db-1                             | cat: can't open '/tmp/.X11-unix/22': No such file or directory
safe-transaction-service-db-1                             | cat: can't open '/tmp/.pg_stat.0': No such file or directory
safe-transaction-service-db-1                             | cat: can't open '/tmp/.pg_stat.1': No such file or directory
safe-transaction-service-db-1                             | cat: can't open '/var/lib/postgresql/data/./oka.pid': No such file or directory
safe-transaction-service-db-1                             | ps: unrecognized option: w
safe-transaction-service-db-1                             | BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | Usage: ps [-o COL1,COL2=HEADER] [-T]
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | Show list of processes
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | 	-o COL1,COL2=HEADER	Select columns for display
safe-transaction-service-db-1                             | 	-T			Show threads
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:49.944 * Trying a partial resynchronization (request 9ca52b6ed8b72933907590de9622b998b35ad783:1).
safe-transaction-service-db-1                             | ps: unrecognized option: w
safe-transaction-service-db-1                             | BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary.
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | Usage: ps [-o COL1,COL2=HEADER] [-T]
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | Show list of processes
safe-transaction-service-db-1                             | 
safe-transaction-service-db-1                             | 	-o COL1,COL2=HEADER	Select columns for display
safe-transaction-service-db-1                             | 	-T			Show threads
safe-transaction-service-db-1                             | kill: invalid number 'USER'
safe-transaction-service-db-1                             | grep: bad regex 'kworker -c\': Trailing backslash
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:50.377 * Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:1
safe-transaction-service-redis-1                          | 1:S 05 Jan 2023 08:40:50.377 * MASTER <-> REPLICA sync: receiving 55664 bytes from master to disk
safe-transaction-service-db-1                             | kill: invalid number 'USER'
safe-transaction-service-db-1                             | kill: invalid number 'postgres'
safe-transaction-service-db-1                             | kill: invalid number 'postgres'
safe-transaction-service-db-1                             | bash: line 249: systemctl: command not found
safe-transaction-service-db-1                             | killall: log_rot: no process killed
safe-transaction-service-db-1                             | chattr: can't stat '/etc/ld.so.preload': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/1.sh': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/1.sh.1': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/1.sh.2': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/1.sh.3': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/3.sh': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/3.sh.1': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/3.sh.2': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/opt/atlassian/confluence/bin/3.sh.3': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/var/tmp/lib': No such file or directory
safe-transaction-service-db-1                             | rm: can't remove '/var/tmp/.lib': No such file or directory
safe-transaction-service-db-1                             | chattr: can't stat '/tmp/lok': No such file or directory
safe-transaction-service-db-1                             | chmod: /tmp/lok: No such file or directory
safe-transaction-service-db-1                             | bash: line 551: docker: command not found
safe-transaction-service-db-1                             | bash: line 552: docker: command not found
safe-transaction-service-db-1                             | bash: line 553: docker: command not found
safe-transaction-service-db-1                             | bash: line 554: docker: command not found
safe-transaction-service-db-1                             | bash: line 555: docker: command not found
safe-transaction-service-db-1                             | bash: line 556: docker: command not found
safe-transaction-service-db-1                             | bash: line 557: docker: command not found
safe-transaction-service-db-1                             | bash: line 558: docker: command not found
safe-transaction-service-db-1                             | bash: line 559: docker: command not found
safe-transaction-service-db-1                             | bash: line 560: docker: command not found
safe-transaction-service-db-1                             | bash: line 561: docker: command not found
safe-transaction-service-db-1                             | bash: line 562: docker: command not found
safe-transaction-service-db-1                             | bash: line 563: docker: command not found
safe-transaction-service-db-1                             | bash: line 564: docker: command not found
safe-transaction-service-db-1                             | bash: line 565: docker: command not found
safe-transaction-service-db-1                             | bash: line 566: docker: command not found
safe-transaction-service-db-1                             | bash: line 567: docker: command not found
safe-transaction-service-db-1                             | bash: line 568: docker: command not found
safe-transaction-service-db-1                             | bash: line 569: docker: command not found
safe-transaction-service-db-1                             | bash: line 570: docker: command not found
safe-transaction-service-db-1                             | bash: line 571: docker: command not found
safe-transaction-service-db-1                             | bash: line 572: docker: command not found
safe-transaction-service-db-1                             | bash: line 573: setenforce: command not found
safe-transaction-service-db-1                             | bash: line 574: /etc/selinux/config: No such file or directory
safe-transaction-service-db-1                             | bash: line 575: service: command not found
safe-transaction-service-db-1                             | bash: line 576: systemctl: command not found
safe-transaction-service-db-1                             | bash: line 577: service: command not found
safe-transaction-service-db-1                             | bash: line 578: systemctl: command not found
safe-transaction-service-db-1                             | md5sum: can't open '/tmp/kinsing': No such file or directory
safe-transaction-service-db-1                             | /tmp/kinsing is not 2c44b4e4706b8bd95d1866d7867efa0e, actual 
safe-transaction-service-db-1                             | chmod: /tmp/kinsing: No such file or directory
safe-transaction-service-db-1                             | Connecting to 185.246.90.205 (185.246.90.205:80)
safe-transaction-service-scheduler-1                      | 2023-01-05 08:40:53,625 [INFO] [???/???] Scheduler: Sending due task Index new Proxies (safe_transaction_service.history.tasks.index_new_proxies_task)
safe-transaction-service-indexer-worker-1                 | 2023-01-05 08:40:53,645 [ERROR] [b9ccebf4/index_new_proxies_task] Task safe_transaction_service.history.tasks.index_new_proxies_task[b9ccebf4-9fd9-4325-b81a-8087edeb199c] raised unexpected: ReadOnlyError("You can't write against a read only replica.")
```

**Comment by steliyannedev** [comment]
configuration issue
