### ISSUE TITLE
Temporary failure in name resolution when running task index_new_proxies_task

### ISSUE THREAD

**Issue by Uponn** [safe-global/safe-transaction-service#1288]
**Describe the bug**
The transaction service keeps crashing making various safe related features in the client freeze, seems the issue is with redis. The redis and the task in question are working fine at the beginning but later on crashes or closes the connection as you will see in the error logs. Only way to fix it restart the either the redis service or the whole transaction service altogether

**To Reproduce**
happens randomly when trying to execute tash: safe_transaction_service.history.tasks.index_new_proxies_task[6f297a82-6c37-4a3d-8ffa-e86187da08ce]

**Environment (please complete the following information):**
 - Staging or production? - staging
 - Which chain? - custom chain
 - OS: [e.g. iOS] - linux
 - Browser [e.g. chrome, safari] - any

**Additional context**
Logs: 
```
redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
2023-01-13 23:04:39,395 [ERROR] [6f297a82/index_new_proxies_task] Task safe_transaction_service.history.tasks.index_new_proxies_task[6f297a82-6c37-4a3d-8ffa-e86187da08ce] raised unexpected: ConnectionError('Error -3 connecting to redis:6379. Temporary failure in name resolution.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 645, in _connect
    for res in socket.getaddrinfo(
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.10/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/local/lib/python3.10/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
  File "src/gevent/event.py", line 329, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 359, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 347, in gevent._gevent_cevent.AsyncResult.get
  File "src/gevent/event.py", line 327, in gevent._gevent_cevent.AsyncResult._raise_exception
  File "/usr/local/lib/python3.10/site-packages/gevent/_compat.py", line 66, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/gevent/threadpool.py", line 173, in __run_task
    thread_result.set(func(*args, **kwargs))
socket.gaierror: [Errno -3] Temporary failure in name resolution
```
the transaction service version that I'm using is ```4.11.2```.

**Comment by Uxio0** [comment]
Issue is not related to redis, it's related to docker which is the one doing the name resolution.

Also, we cannot support a transaction service version from October, please update to the last version both the service and docker/docker compose.
