### ISSUE TITLE
Blocking with tx-service error logs

### ISSUE THREAD

**Issue by Sj-001** [safe-global/safe-transaction-service#1420]
@DmitryBespalov @svanegmond 

```
2023-04-17 17:19:48,539 [WARNING] [b73f2ffc/index_erc20_events_task] Erc20EventsIndexer: Value error retrieving events from-block=203477034 to-block=203477034 : {'code': -32602, 'message': 'bad topic None'}
2023-04-17 17:19:48,539 [INFO] [b73f2ffc/index_erc20_events_task] Erc20EventsIndexer: block_process_limit set back to 1
2023-04-17 17:19:48,539 [DEBUG] [b73f2ffc/index_erc20_events_task] DB connection returned to the pool
2023-04-17 17:19:48,550 [ERROR] [b73f2ffc/index_erc20_events_task] Task safe_transaction_service.history.tasks.index_erc20_events_task[b73f2ffc-db1d-4846-bb39-58933efe0e25] raised unexpected: FindRelevantElementsException('Request error retrieving events from-block=203477034 to-block=203477034')
Traceback (most recent call last):
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 172, in _find_elements_using_topics
    return self._do_node_query(addresses, from_block_number, to_block_number)
  File "/app/safe_transaction_service/history/indexers/erc20_events_indexer.py", line 96, in _do_node_query
    transfer_events = self.ethereum_client.erc20.get_total_transfer_history(
  File "/usr/local/lib/python3.10/site-packages/gnosis/eth/ethereum_client.py", line 693, in get_total_transfer_history
    all_events.extend(self.slow_w3.eth.get_logs(parameters))
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'bad topic None'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 54, in run
    ret = task.retry(exc=exc, **retry_kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/task.py", line 717, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/app/safe_transaction_service/history/tasks.py", line 105, in index_erc20_events_task
    ) = Erc20EventsIndexerProvider().start()
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 444, in start
    ) = self.process_addresses(
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 402, in process_addresses
    raise e
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 389, in process_addresses
    elements = self.find_relevant_elements(
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 223, in find_relevant_elements
    log_receipts = self._find_elements_using_topics(
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 190, in _find_elements_using_topics
    raise FindRelevantElementsException(
safe_transaction_service.history.indexers.ethereum_indexer.FindRelevantElementsException: Request error retrieving events from-block=203477034 to-block=203477034
2023-04-17 17:19:50,103 [INFO] [???/???] Task safe_transaction_service.history.tasks.index_new_proxies_task[b407a58f-f4f2-4849-bb65-332f71949ac6] received
```

**Comment by Uxio0** [comment]
This is the first time I see this error. Could you provide more information about what's happening?

- Tx Service version
- RPC you are using

**Comment by Uxio0** [comment]
We cannot reproduce. Is it posible that your node does not support `eth_getLogs` with some parameters?

**Comment by Sj-001** [comment]
> We cannot reproduce. Is it posible that your node does not support `eth_getLogs` with some parameters?

Yes, but I don't see any filter parameters for this block

**Comment by Uxio0** [comment]
Could you paste here the `eth_getLogs` http requesT?

**Comment by Uxio0** [comment]
Closing due to inactivity and not being able to reproduce

**Comment by skimaharvey** [comment]
I am having the same issue here @Uxio0 
```bash 
2023-05-17 04:24:23,349 [INFO] [3c307ffd/index_safe_events_task] Task safe_transaction_service.history.tasks.index_safe_events_task[3c307ffd-b906-42cc-a94e-5ec8e7b41833] succeeded in 0.0786932920000254s: (0, 0)
2023-05-17 04:24:23,475 [INFO] [???/???] Task safe_transaction_service.history.tasks.index_erc20_events_task[9ec58286-6f2d-42da-b361-f22e1d311d07] received
2023-05-17 04:24:23,475 [DEBUG] [???/???] TaskPool: Apply <function fast_trace_task at 0xffff8e13f7f0> (args:('safe_transaction_service.history.tasks.index_erc20_events_task', '9ec58286-6f2d-42da-b361-f22e1d311d07', {'lang': 'py', 'task': 'safe_transaction_service.history.tasks.index_erc20_events_task', 'id': '9ec58286-6f2d-42da-b361-f22e1d311d07', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [900, 600], 'root_id': '9ec58286-6f2d-42da-b361-f22e1d311d07', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@03f953e92919', 'ignore_result': True, 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'lang': 'py', 'task': 'safe_transaction_service.history.tasks.index_erc20_events_task', 'id': '9ec58286-6f2d-42da-b361-f22e1d311d07', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [900, 600], 'root_id': '9ec58286-6f2d-42da-b361-f22e1d311d07', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1@03f953e92919',... kwargs:{})
2023-05-17 04:24:23,477 [INFO] [9ec58286/index_erc20_events_task] Start indexing of erc20/721 events
2023-05-17 04:24:23,477 [DEBUG] [9ec58286/index_erc20_events_task] Making request HTTP. URI: https://rpc.testnet.lukso.network/, Method: eth_blockNumber
2023-05-17 04:24:23,547 [DEBUG] [9ec58286/index_erc20_events_task] Getting response HTTP. URI: https://rpc.testnet.lukso.network/, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 142, 'result': '0x17b9d'}
2023-05-17 04:24:23,547 [DEBUG] [9ec58286/index_erc20_events_task] Erc20EventsIndexer: Current RPC block number=97181
2023-05-17 04:24:23,547 [DEBUG] [9ec58286/index_erc20_events_task] Erc20EventsIndexer: Retrieving monitored addresses
2023-05-17 04:24:23,547 [DEBUG] [9ec58286/index_erc20_events_task] Erc20EventsIndexer: Retrieved monitored addresses
2023-05-17 04:24:23,548 [DEBUG] [9ec58286/index_erc20_events_task] DB connection reused
2023-05-17 04:24:23,550 [INFO] [9ec58286/index_erc20_events_task] Erc20EventsIndexer: Processing 52 almost updated addresses
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/app/safe_transaction_service/utils/celery.py", line 32, in format
    return super().format(record)
  File "/usr/local/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/gevent.py", line 26, in apply_timeout
    return apply_target(target, args, kwargs, callback,
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/app/safe_transaction_service/history/tasks.py", line 106, in index_erc20_events_task
    ) = Erc20EventsIndexerProvider().start()
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 450, in start
    logger.debug(
Message: '%s: Processed %d elements for almost updated addresses. From-block-number=%d to-block-number=%d'
Arguments: ('Erc20EventsIndexer', 0, None, 97181)
```

Tested `eth_Logs` on a NFT contract:

```ts
[
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200'
    ],
    data: '0x',
    blockNumber: '0x17b74',
    transactionHash: '0xf6525dee9895cd2eacf2bdac33dd77518b35453bc4c1ff3e8a3c570e5bf29f59',
    transactionIndex: '0x0',
    blockHash: '0x7eff3b1a3a8f7425275d1b511bb460e37ecae49c8157f96e0096fce6f7d4c1e9',
    logIndex: '0x0',
    removed: false
  },
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200',
      '0x0000000000000000000000000000000000000000000000000000000000000000'
    ],
    data: '0x',
    blockNumber: '0x17b7b',
    transactionHash: '0xa1c4cbe392230538b7c6de0a1ee2500e7a2ccc260cbe6028bdf63514091ee443',
    transactionIndex: '0x0',
    blockHash: '0x9c8ed08d4e9091d169daf41eb2c5a9f728c592599c12b67f290721c8ba62bd22',
    logIndex: '0x0',
    removed: false
  },
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200',
      '0x0000000000000000000000006c36b9aa78a49c1070abff2a4975b5df40d77eac',
      '0x0000000000000000000000000000000000000000000000000000000000000000'
    ],
    data: '0x',
    blockNumber: '0x17b8b',
    transactionHash: '0x9a30526f3947acd4ee7e52d3549c6071a3bcc0b18b79d73c834e0a060f19b08c',
    transactionIndex: '0x0',
    blockHash: '0xed838a6087c034ebc969900bc935c67394fb745fc050d5ea5d8368434fa32d42',
    logIndex: '0x0',
    removed: false
  }
]
```
