### ISSUE TITLE
Indexing of ERC20 events throwing error in the indexer worker

### ISSUE THREAD

**Issue by skimaharvey** [safe-global/safe-transaction-service#1471]
**Cannot Index ERC20 transfer**
I have the following error in the indexer worker of the safe transaction service when trying to index erc20 events:
```bash
2023-05-17 20:48:47,297 [INFO] [6a86a567/index_erc20_events_task] Start indexing of erc20/721 events
2023-05-17 20:48:47,298 [DEBUG] [6a86a567/index_erc20_events_task] Making request HTTP. URI: http://rpc_url, Method: eth_blockNumber
2023-05-17 20:48:47,407 [DEBUG] [6a86a567/index_erc20_events_task] Getting response HTTP. URI: http://rpc_url, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 109, 'result': '0x18ecc'}
2023-05-17 20:48:47,408 [DEBUG] [6a86a567/index_erc20_events_task] Erc20EventsIndexer: Current RPC block number=102092
2023-05-17 20:48:47,408 [DEBUG] [6a86a567/index_erc20_events_task] Erc20EventsIndexer: Retrieving monitored addresses
2023-05-17 20:48:47,409 [DEBUG] [6a86a567/index_erc20_events_task] Erc20EventsIndexer: Retrieved monitored addresses
2023-05-17 20:48:47,416 [DEBUG] [6a86a567/index_erc20_events_task] DB connection reused
2023-05-17 20:48:47,424 [INFO] [6a86a567/index_erc20_events_task] Erc20EventsIndexer: Processing 73 almost updated addresses
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/app/safe_transaction_service/utils/celery.py", line 32, in format
    return super().format(record)
  File "/usr/local/lib/python3.10/site-packages/celery/utils/log.py", line 146, in format
    msg = super().format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not NoneType
Call stack:
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/gevent.py", line 26, in apply_timeout
    return apply_target(target, args, kwargs, callback,
  File "/usr/local/lib/python3.10/site-packages/celery/concurrency/base.py", line 29, in apply_target
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 649, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "/app/safe_transaction_service/history/tasks.py", line 106, in index_erc20_events_task
    ) = Erc20EventsIndexerProvider().start()
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 450, in start
    logger.debug(
Message: '%s: Processed %d elements for almost updated addresses. From-block-number=%d to-block-number=%d'
Arguments: ('Erc20EventsIndexer', 0, None, 102092)
2023-05-17 20:48:47,429 [DEBUG] [6a86a567/index_erc20_events_task] Erc20EventsIndexer: No not updated addresses to process
2023-05-17 20:48:47,435 [DEBUG] [6a86a567/index_erc20_events_task] Indexing of erc20/721 events task processed 0 events
2023-05-17 20:48:47,436 [DEBUG] [6a86a567/index_erc20_events_task] DB connection returned to the pool
```

**To Reproduce**
I am running the safe-infrastructure. The creation of safes and the indexing of native tokens transactions is working great (with tracing and events modes)

**Expected behavior**
Should not throw any error and also should index tokens transfers

**Environment (please complete the following information):**
 - running the safe-infrastructure locally
 - testnet (fork of ethereum with events logging working - `eth_Logs` method working fine)
 - running docker containers
 - Chrome
 - lastest version of the images providing in the safe-infrastructure

**Additional Context** 

`eth_Logs` returns that: 

```bash 
[
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200'
    ],
    data: '0x',
    blockNumber: '0x17b74',
    transactionHash: '0xf6525dee9895cd2eacf2bdac33dd77518b35453bc4c1ff3e8a3c570e5bf29f59',
    transactionIndex: '0x0',
    blockHash: '0x7eff3b1a3a8f7425275d1b511bb460e37ecae49c8157f96e0096fce6f7d4c1e9',
    logIndex: '0x0',
    removed: false
  },
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000000000000000000000000000000000000000000000',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200',
      '0x0000000000000000000000000000000000000000000000000000000000000000'
    ],
    data: '0x',
    blockNumber: '0x17b7b',
    transactionHash: '0xa1c4cbe392230538b7c6de0a1ee2500e7a2ccc260cbe6028bdf63514091ee443',
    transactionIndex: '0x0',
    blockHash: '0x9c8ed08d4e9091d169daf41eb2c5a9f728c592599c12b67f290721c8ba62bd22',
    logIndex: '0x0',
    removed: false
  },
  {
    address: '0xfb10a65e5f0402b8e9d4ca84d0f367f0779cc67f',
    topics: [
      '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
      '0x0000000000000000000000000ecc079c20daa9fde0e26b6d745c0b38479ff200',
      '0x0000000000000000000000006c36b9aa78a49c1070abff2a4975b5df40d77eac',
      '0x0000000000000000000000000000000000000000000000000000000000000000'
    ],
    data: '0x',
    blockNumber: '0x17b8b',
    transactionHash: '0x9a30526f3947acd4ee7e52d3549c6071a3bcc0b18b79d73c834e0a060f19b08c',
    transactionIndex: '0x0',
    blockHash: '0xed838a6087c034ebc969900bc935c67394fb745fc050d5ea5d8368434fa32d42',
    logIndex: '0x0',
    removed: false
  }
]
```

**Comment by Uxio0** [comment]
Did you change something on the database? You should have a table `IndexingStatus` in your database with the current block for indexing erc20, and that should be `0`

**Comment by skimaharvey** [comment]
You are correct. For some reason, I had a block number higher than the current one for `ERC20_721_EVENTS`.
It is working now 🙏
