### ISSUE TITLE
Worker stops to consume tasks after "connection reset by peer"

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#1566]
**Describe the bug**
Celery worker stops to consume tasks after connectionResetError
```
2023-07-13 04:44:56,439 [CRITICAL] [???/???] Couldn't ack 2351, reason:ConnectionResetError(104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/kombu/message.py", line 131, in ack_log_error
    self.ack(multiple=multiple)
  File "/usr/local/lib/python3.10/site-packages/kombu/message.py", line 126, in ack
    self.channel.basic_ack(self.delivery_tag, multiple=multiple)
  File "/usr/local/lib/python3.10/site-packages/amqp/channel.py", line 1407, in basic_ack
    return self.send_method(
  File "/usr/local/lib/python3.10/site-packages/amqp/abstract_channel.py", line 70, in send_method
    conn.frame_writer(1, self.channel_id, sig, args, content)
  File "/usr/local/lib/python3.10/site-packages/amqp/method_framing.py", line 186, in write_frame
    write(buffer_store.view[:offset])
  File "/usr/local/lib/python3.10/site-packages/amqp/transport.py", line 347, in write
    self._write(s)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
```
**Expected behavior**
Connection errors can happen but the worker should handle to reconnect and continue consuming tasks.

**Comment by Uxio0** [comment]
After updating RabbitMQ/Redis we haven't seen this issue again

**Comment by alfredolopez80** [comment]
@Uxio0 can you give us more details about it?, how updating RabbitMQ, or commit reference?

**Comment by Uxio0** [comment]
There's no commit, you must update RabbitMQ in your infrastructure

**Comment by alfredolopez80** [comment]
> There's no commit, you must update RabbitMQ in your infrastructure

thks for your answer @Uxio0 but we use rabbitmq:alpine, we asume is the last version always? o require additional settings? can you give me some additional advice or details if have time!!

**Comment by Uxio0** [comment]
@alfredolopez80 I'm not getting you and also I don´t know details of your infrastructure, but `rabbitmq:alpine` should point to the last version

**Comment by alfredolopez80** [comment]
> @alfredolopez80 I'm not getting you and also I don´t know details of your infrastructure, but `rabbitmq:alpine` should point to the last version

first at all, thks your soon answer

> There's no commit, you must update RabbitMQ in your infrastructure

can you with me more details or example of that!!, RabbitMQ require more resources? or what your update in the safe infrastructure about RabbitMQ?

because we have the same behavior indicate in these thread!!, and don't have clear about what happend with RabbitMQ services!!

**Comment by moisses89** [comment]
@Uxio0 I added a PR to revert celery to the previous version. 
This PR is going to close this issue, if the issues with rabbitMQ connection happens again we can reopen this issue.

**Comment by moisses89** [comment]
> because we have the same behavior indicate in these thread!!, and we don't have clear the cause

@alfredolopez80 are you having issues with this project or other project using django+celery? have you the celery version 5.3.1 also?

**Comment by Uxio0** [comment]
@alfredolopez80 you shouldn't be updating any library and just use the last docker version of the tx service, we handle that

**Comment by moisses89** [comment]
Reopening the issue to track it due happened again.
