### ISSUE TITLE
Error FindRelevantElementsException request error retrieving events from block 0 to block 0 from safe_transaction_service.history.tasks.index_erc20_events_task

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-transaction-service#2127]
txs-service version: 5.2.2

Below is the error from txs-worker-indexer, is there something that we need to configure?

I can see some indexing is happening
```
2024-07-09 06:08:54,329 [INFO] [fcbb3b2c/index_safe_events_task] Start indexing of Safe events
2024-07-09 06:08:54,329 [DEBUG] [fcbb3b2c/index_safe_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545,
Method: eth_blockNumber
2024-07-09 06:08:54,337 [DEBUG] [fcbb3b2c/index_safe_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 24, 'result': '0xe7a1a7'}
2024-07-09 06:08:54,337 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Current RPC block number=15180199
2024-07-09 06:08:54,337 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Retrieving almost updated monitored addresses
2024-07-09 06:08:54,337 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Getting minimum-block-number for all the addresses
2024-07-09 06:08:54,338 [DEBUG] [fcbb3b2c/index_safe_events_task] DB connection reused
2024-07-09 06:08:54,339 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Got minimum-block-number=15180199
2024-07-09 06:08:54,340 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Retrieved almost updated monitored addresses
2024-07-09 06:08:54,340 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: No almost updated addresses to process
2024-07-09 06:08:54,340 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Retrieving not updated monitored addresses
2024-07-09 06:08:54,341 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Retrieved not updated monitored addresses
2024-07-09 06:08:54,341 [INFO] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Processing not updated addresses
2024-07-09 06:08:54,341 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Getting minimum-block-number for 1 addresses
2024-07-09 06:08:54,342 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Got minimum-block-number=15180199
2024-07-09 06:08:54,342 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Filtering for events from block-number=15180197 to block-number=15180199 for 1 addresses
2024-07-09 06:08:54,342 [DEBUG] [fcbb3b2c/index_safe_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545,
Method: eth_getLogs
2024-07-09 06:08:54,351 [DEBUG] [fcbb3b2c/index_safe_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs, Response: {'jsonrpc': '2.0', 'id': 21, 'result': []}
2024-07-09 06:08:54,351 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Found 0 events from block-number=15180197 to block-number=15180199 for 1 addresses
2024-07-09 06:08:54,351 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Updating monitored addresses
2024-07-09 06:08:54,352 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Updated monitored addresses
2024-07-09 06:08:54,352 [DEBUG] [fcbb3b2c/index_safe_events_task] SafeEventsIndexer: Processed 0 elements for not updated addresses. From-block-number=15180197 to-block-number=15180199
2024-07-09 06:08:54,352 [INFO] [fcbb3b2c/index_safe_events_task] Find Safe events processed 0 events
2024-07-09 06:08:54,352 [DEBUG] [fcbb3b2c/index_safe_events_task] DB connection returned to the pool
2024-07-09 06:08:54,364 [INFO] [fcbb3b2c/index_safe_events_task] Task safe_transaction_service.history.tasks.index_safe_events_task[fcbb3b2c-b851-44e5-ae79-5279150d62fe] succeeded in 0.03545955917797983s: (0, 3)
2024-07-09 06:08:54,406 [DEBUG] [???/???] TaskPool: Apply <function fast_trace_task at 0x7f288862b600> (args:('safe_transaction_service.history.tasks.index_erc20_events_task', 'd5131e91-8f8c-400f-bc42-b183443caed3', {'argsrepr': '()', 'eta': '2024-07-09T06:08:54.406881+00:00', 'expires': None, 'group': None, 'group_index': None, 'id': 'd5131e91-8f8c-400f-bc42-b183443caed3', 'ignore_result': True, 'kwargsrepr': '{}',
'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': 'd5131e91-8f8c-400f-bc42-b183443caed3', 'replaced_task_nesting': 0, 'retries': 3,
'root_id': 'd5131e91-8f8c-400f-bc42-b183443caed3', 'shadow': None, 'stamped_headers': None, 'stamps': {}, 'task': 'safe_transaction_service.history.tasks.index_erc20_events_task', 'timelimit': [900, 600], 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'argsrepr': '()', 'eta': '2024-07-09T06:08:54.406881+00:00', 'expires': None, 'group': None, 'group_index': None, 'id': 'd5131e91-8f8c-400f-bc42-b183443caed3', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id':... kwargs:{})
2024-07-09 06:08:54,407 [INFO] [d5131e91/index_erc20_events_task] Start indexing of erc20/721 events
2024-07-09 06:08:54,407 [DEBUG] [d5131e91/index_erc20_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_blockNumber
2024-07-09 06:08:54,433 [DEBUG] [d5131e91/index_erc20_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 30, 'result': '0xe7a1a7'}
2024-07-09 06:08:54,433 [DEBUG] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Current RPC block number=15180199
2024-07-09 06:08:54,433 [DEBUG] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Retrieving monitored addresses
2024-07-09 06:08:54,434 [DEBUG] [d5131e91/index_erc20_events_task] DB connection reused
2024-07-09 06:08:54,434 [DEBUG] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Retrieved monitored addresses
2024-07-09 06:08:54,434 [INFO] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Processing almost updated addresses
2024-07-09 06:08:54,435 [DEBUG] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Filtering for events from block-number=0 to block-number=0 for 3 addresses
2024-07-09 06:08:54,435 [DEBUG] [d5131e91/index_erc20_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs
2024-07-09 06:08:54,443 [DEBUG] [d5131e91/index_erc20_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs, Response: {'jsonrpc': '2.0', 'id': 29, 'error': {'code': -32000, 'message': 'maximum [from, to] blocks distance: 10000'}}
2024-07-09 06:08:54,443 [WARNING] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: Value error retrieving events from-block=0 to-block=0 : {'code': -32000, 'message': 'maximum [from, to] blocks distance: 10000'}
2024-07-09 06:08:54,443 [INFO] [d5131e91/index_erc20_events_task] Erc20EventsIndexer: block_process_limit set back to 1
2024-07-09 06:08:54,444 [DEBUG] [d5131e91/index_erc20_events_task] DB connection returned to the pool
2024-07-09 06:08:54,452 [ERROR] [d5131e91/index_erc20_events_task] Task safe_transaction_service.history.tasks.index_erc20_events_task[d5131e91-8f8c-400f-bc42-b183443caed3] raised unexpected: FindRelevantElementsException('Request error retrieving events from-block=0 to-block=0')
Traceback (most recent call last):
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 150, in _find_elements_using_topics
    return self._do_node_query(addresses, from_block_number, to_block_number)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/indexers/erc20_events_indexer.py", line 106, in _do_node_query
    transfer_events = self.ethereum_client.erc20.get_total_transfer_history(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 719, in get_total_transfer_history
    for event in self.slow_w3.eth.get_logs(parameters):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/eth/eth.py", line 456, in get_logs
    return self._get_logs(filter_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 330, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 293, in formatted_response
    raise ValueError(error)
ValueError: {'code': -32000, 'message': 'maximum [from, to] blocks distance: 10000'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/tasks.py", line 110, in index_erc20_events_task
    ) = Erc20EventsIndexerProvider().start()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 465, in start
    ) = self.process_addresses(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 422, in process_addresses
    raise e
  File "/app/safe_transaction_service/history/indexers/ethereum_indexer.py", line 403, in process_addresses
    elements = self.find_relevant_elements(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 201, in find_relevant_elements
    log_receipts = self._find_elements_using_topics(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/indexers/events_indexer.py", line 168, in _find_elements_using_topics
    raise FindRelevantElementsException(
safe_transaction_service.history.indexers.ethereum_indexer.FindRelevantElementsException: Request error retrieving events from-block=0 to-block=0
2024-07-09 06:08:59,305 [INFO] [???/???] Task safe_transaction_service.history.tasks.index_new_proxies_task[f328274c-1a8a-48ce-9fd3-32b2b42e16ae] received
2024-07-09 06:08:59,306 [DEBUG] [???/???] TaskPool: Apply <function fast_trace_task at 0x7f288862b600> (args:('safe_transaction_service.history.tasks.index_new_proxies_task', 'f328274c-1a8a-48ce-9fd3-32b2b42e16ae', {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'f328274c-1a8a-48ce-9fd3-32b2b42e16ae', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'f328274c-1a8a-48ce-9fd3-32b2b42e16ae', 'shadow': None, 'stamped_headers': None, 'stamps': {}, 'task': 'safe_transaction_service.history.tasks.index_new_proxies_task', 'timelimit': [900, 600], 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'f328274c-1a8a-48ce-9fd3-32b2b42e16ae', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'f328274c-1a8a-48ce-9fd3-32b2b42e16ae',... kwargs:{})
2024-07-09 06:08:59,307 [INFO] [f328274c/index_new_proxies_task] Start indexing of new proxies
2024-07-09 06:08:59,308 [DEBUG] [f328274c/index_new_proxies_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545,
Method: eth_blockNumber
2024-07-09 06:08:59,327 [INFO] [???/???] Task safe_transaction_service.history.tasks.index_safe_events_task[f6b57107-64f1-49a4-af3a-74a543b8ebfc] received
2024-07-09 06:08:59,328 [DEBUG] [???/???] TaskPool: Apply <function fast_trace_task at 0x7f288862b600> (args:('safe_transaction_service.history.tasks.index_safe_events_task', 'f6b57107-64f1-49a4-af3a-74a543b8ebfc', {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'f6b57107-64f1-49a4-af3a-74a543b8ebfc', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'f6b57107-64f1-49a4-af3a-74a543b8ebfc', 'shadow': None, 'stamped_headers': None, 'stamps': {}, 'task': 'safe_transaction_service.history.tasks.index_safe_events_task', 'timelimit': [900, 600], 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'f6b57107-64f1-49a4-af3a-74a543b8ebfc', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'f6b57107-64f1-49a4-af3a-74a543b8ebfc',... kwargs:{})
2024-07-09 06:08:59,329 [INFO] [f6b57107/index_safe_events_task] Start indexing of Safe events
2024-07-09 06:08:59,329 [DEBUG] [f6b57107/index_safe_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545,
Method: eth_blockNumber
2024-07-09 06:08:59,331 [DEBUG] [f328274c/index_new_proxies_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 9, 'result': '0xe7a1a8'}
2024-07-09 06:08:59,331 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Current RPC block number=15180200
2024-07-09 06:08:59,331 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Retrieving almost updated monitored addresses
2024-07-09 06:08:59,331 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Getting minimum-block-number for all the addresses
2024-07-09 06:08:59,332 [DEBUG] [f328274c/index_new_proxies_task] DB connection reused
2024-07-09 06:08:59,333 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Got minimum-block-number=15180198
2024-07-09 06:08:59,334 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Retrieved almost updated monitored addresses
2024-07-09 06:08:59,334 [INFO] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Processing almost updated addresses
2024-07-09 06:08:59,334 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Getting minimum-block-number for 1 addresses
2024-07-09 06:08:59,335 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Got minimum-block-number=15180198
2024-07-09 06:08:59,335 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Filtering for events from block-number=15180196 to block-number=15180200 for 1 addresses
2024-07-09 06:08:59,337 [DEBUG] [???/???] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs
2024-07-09 06:08:59,347 [DEBUG] [???/???] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs, Response: {'jsonrpc': '2.0', 'id': 8, 'result': []}
2024-07-09 06:08:59,347 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Found 0 events from block-number=15180196 to block-number=15180200 for 1 addresses
2024-07-09 06:08:59,347 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Updating monitored addresses
2024-07-09 06:08:59,348 [DEBUG] [f6b57107/index_safe_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_blockNumber, Response: {'jsonrpc': '2.0', 'id': 25, 'result': '0xe7a1a8'}
2024-07-09 06:08:59,348 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Current RPC block number=15180200
2024-07-09 06:08:59,348 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Retrieving almost updated monitored addresses
2024-07-09 06:08:59,348 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Getting minimum-block-number for all the addresses
2024-07-09 06:08:59,349 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Updated monitored addresses
2024-07-09 06:08:59,349 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Processed 0 elements for almost updated addresses. From-block-number=15180196 to-block-number=15180200
2024-07-09 06:08:59,349 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Retrieving not updated monitored addresses
2024-07-09 06:08:59,350 [DEBUG] [f6b57107/index_safe_events_task] DB connection reused
2024-07-09 06:08:59,350 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: Retrieved not updated monitored addresses
2024-07-09 06:08:59,350 [DEBUG] [f328274c/index_new_proxies_task] ProxyFactoryIndexer: No not updated addresses to process
2024-07-09 06:08:59,350 [INFO] [f328274c/index_new_proxies_task] Proxy indexing found 0 proxies
2024-07-09 06:08:59,350 [DEBUG] [f328274c/index_new_proxies_task] DB connection returned to the pool
2024-07-09 06:08:59,351 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Got minimum-block-number=15180200
2024-07-09 06:08:59,364 [INFO] [f328274c/index_new_proxies_task] Task safe_transaction_service.history.tasks.index_new_proxies_task[f328274c-1a8a-48ce-9fd3-32b2b42e16ae] succeeded in 0.05689120199531317s: (0, 5)
2024-07-09 06:08:59,365 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Retrieved almost updated monitored addresses
2024-07-09 06:08:59,365 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: No almost updated addresses to process
2024-07-09 06:08:59,365 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Retrieving not updated monitored addresses
2024-07-09 06:08:59,366 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Retrieved not updated monitored addresses
2024-07-09 06:08:59,366 [INFO] [f6b57107/index_safe_events_task] SafeEventsIndexer: Processing not updated addresses
2024-07-09 06:08:59,366 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Getting minimum-block-number for 1 addresses
2024-07-09 06:08:59,367 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Got minimum-block-number=15180200
2024-07-09 06:08:59,367 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Filtering for events from block-number=15180198 to block-number=15180200 for 1 addresses
2024-07-09 06:08:59,368 [DEBUG] [f6b57107/index_safe_events_task] Making request HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545,
Method: eth_getLogs
2024-07-09 06:08:59,378 [DEBUG] [f6b57107/index_safe_events_task] Getting response HTTP. URI: https://testnet-fx-json-web3.functionx.io:8545, Method: eth_getLogs, Response: {'jsonrpc': '2.0', 'id': 22, 'result': []}
2024-07-09 06:08:59,378 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Found 0 events from block-number=15180198 to block-number=15180200 for 1 addresses
2024-07-09 06:08:59,379 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Updating monitored addresses
2024-07-09 06:08:59,380 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Updated monitored addresses
2024-07-09 06:08:59,380 [DEBUG] [f6b57107/index_safe_events_task] SafeEventsIndexer: Processed 0 elements for not updated addresses. From-block-number=15180198 to-block-number=15180200
2024-07-09 06:08:59,380 [INFO] [f6b57107/index_safe_events_task] Find Safe events processed 0 events
2024-07-09 06:08:59,380 [DEBUG] [f6b57107/index_safe_events_task] DB connection returned to the pool
2024-07-09 06:08:59,392 [INFO] [f6b57107/index_safe_events_task] Task safe_transaction_service.history.tasks.index_safe_events_task[f6b57107-64f1-49a4-af3a-74a543b8ebfc] succeeded in 0.06382633885368705s: (0, 3)
2024-07-09 06:09:00,002 [INFO] [???/???] Task safe_transaction_service.history.tasks.check_reorgs_task[a6575cf9-d055-4b8f-930d-6ed705f89748] received
2024-07-09 06:09:00,002 [DEBUG] [???/???] TaskPool: Apply <function fast_trace_task at 0x7f288862b600> (args:('safe_transaction_service.history.tasks.check_reorgs_task', 'a6575cf9-d055-4b8f-930d-6ed705f89748', {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'a6575cf9-d055-4b8f-930d-6ed705f89748', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'a6575cf9-d055-4b8f-930d-6ed705f89748', 'shadow': None, 'stamped_headers': None, 'stamps': {}, 'task': 'safe_transaction_service.history.tasks.check_reorgs_task', 'timelimit': [900, 600], 'properties': {'content_type': 'application/json', 'content_encoding': 'utf-8', 'application_headers': {'argsrepr': '()', 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'id': 'a6575cf9-d055-4b8f-930d-6ed705f89748', 'ignore_result': True, 'kwargsrepr': '{}', 'lang': 'py', 'origin': 'gen1@afdd05fe1de2', 'parent_id': None, 'replaced_task_nesting': 0, 'retries': 0, 'root_id': 'a6575cf9-d055-4b8f-930d-6ed705f89748', 'shadow':... kwargs:{})
2024-07-09 06:09:00,004 [INFO] [a6575cf9/check_reorgs_task] Start checking of reorgs
2024-07-09 06:09:00,004 [DEBUG] [a6575cf9/check_reorgs_task] DB connection reused
2024-07-09 06:09:00,005 [INFO] [a6575cf9/check_reorgs_task] No reorg was found
2024-07-09 06:09:00,005 [DEBUG] [a6575cf9/check_reorgs_task] DB connection returned to the pool
2024-07-09 06:09:00,016 [INFO] [a6575cf9/check_reorgs_task] Task safe_transaction_service.history.tasks.check_reorgs_task[a6575cf9-d055-4b8f-930d-6ed705f89748] succeeded in 0.01329114893451333s: None
```

**Comment by lance-web3** [comment]
seems no more error after pull the v5.3.1
