### ISSUE TITLE
indexer not able to rebuild SafeLastStatus

### ISSUE THREAD

**Issue by tolbrino** [safe-global/safe-transaction-service#2148]
**Describe the bug**
The indexer cannot rebuild missing `SafeLastStatus` anymore, failing whenever this code path is executed.
Re-running the migrations did not help.

**To Reproduce**
The indexer got into this state but I am not sure how. Now however, it is stuck like that.

**Expected behavior**
Indexer can rebuild missing `SafeLastStatus`

**Environment (please complete the following information):**
safe-tx-service v5.3.1

**Additional context**

```
safe-transaction-indexer-6d86bcf4b8-kd64l indexer 2024-07-17 06:06:25,708 [ERROR] [9e734920/process_decoded_internal_txs_for_safe_task] Task safe_transaction_service.history.tasks.process_decoded_internal_txs_for_safe_task[9e734920-2123-4d21-bad6-c553395d50e5] raised unexpected: DoesNotExist('SafeLastStatus matching query does not exist.')
safe-transaction-indexer-6d86bcf4b8-kd64l indexer Traceback (most recent call last):
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     R = retval = fun(*args, **kwargs)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer                  ^^^^^^^^^^^^^^^^^^^^
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     return self.run(*args, **kwargs)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer            ^^^^^^^^^^^^^^^^^^^^^^^^^
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/app/safe_transaction_service/history/tasks.py", line 462, in process_decoded_internal_txs_for_safe_task
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     index_service.fix_out_of_order(
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     return func(*args, **kwds)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer            ^^^^^^^^^^^^^^^^^^^
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/app/safe_transaction_service/history/services/index_service.py", line 385, in fix_out_of_order
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     SafeLastStatus.objects.get_or_generate(address)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/app/safe_transaction_service/history/models.py", line 1884, in get_or_generate
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     return SafeLastStatus.objects.get(address=address)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     return getattr(self.get_queryset(), name)(*args, **kwargs)
safe-transaction-indexer-6d86bcf4b8-kd64l indexer            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-transaction-indexer-6d86bcf4b8-kd64l indexer   File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 649, in get
safe-transaction-indexer-6d86bcf4b8-kd64l indexer     raise self.model.DoesNotExist(
safe-transaction-indexer-6d86bcf4b8-kd64l indexer safe_transaction_service.history.models.SafeLastStatus.DoesNotExist: SafeLastStatus matching query does not exist.
```

**Comment by Uxio0** [comment]
Thanks for reporting, it was fixed in our last release by https://github.com/safe-global/safe-transaction-service/pull/2146
