### ISSUE TITLE
Error loading transaction history when UI querying cgw querying transaction service

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-transaction-service#2185]
**Describe the bug**
Error loading transaction history on UI (Refer to below screenshot)

txs-service-web log:
```
2024-08-14 01:47:51,564 MT::GET::api/v1/about/singletons/::4::200::/api/v1/about/singletons/
2024-08-14 01:47:51,639 MT::GET::api/v1/safes/<str:address>/balances/::14::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/balances/
2024-08-14 01:47:51,705 MT::GET::api/v1/safes/<str:address>/::136::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/
2024-08-14 01:47:51,744 MT::GET::api/v1/safes/<str:address>/transfers/::17::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/transfers/
2024-08-14 01:47:51,744 MT::GET::api/v1/safes/<str:address>/multisig-transactions/::18::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/multisig-transactions/
2024-08-14 01:47:51,746 MT::GET::api/v1/safes/<str:address>/transfers/::32::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/transfers/
2024-08-14 01:47:51,748 MT::GET::api/v1/safes/<str:address>/multisig-transactions/::31::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/multisig-transactions/
2024-08-14 01:47:51,751 MT::GET::api/v1/safes/<str:address>/messages/::10::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/messages/
2024-08-14 01:47:51,752 MT::GET::api/v1/contracts/<str:address>/::5::404::/api/v1/contracts/0x29fcB43b46531BcA003ddC8FCB67FFE91900C762/
2024-08-14 01:47:51,755 MT::GET::api/v1/safes/<str:address>/module-transactions/::20::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/module-transactions/
2024-08-14 01:47:51,759 MT::GET::api/v1/contracts/<str:address>/::17::404::/api/v1/contracts/0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99/
2024-08-14 01:48:00,884 MT::GET::api/v1/safes/<str:address>/multisig-transactions/::12::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/multisig-transactions/
2024-08-14 01:48:00,934 MT::GET::api/v1/safes/<str:address>/all-transactions/::3::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/all-transactions/
2024-08-14 01:48:00,946 MT::GET::api/v1/safes/<str:address>/messages/::4::200::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/messages/
2024-08-14 01:48:00,965 [ERROR] [MainProcess] Internal Server Error: /api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/creation/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/views.py", line 970, in get
    safe_creation_info = SafeServiceProvider().get_safe_creation_info(address)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/services/safe_service.py", line 111, in get_safe_creation_info
    parent_internal_tx = self._get_parent_internal_tx(creation_internal_tx)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/safe_transaction_service/history/services/safe_service.py", line 287, in _get_parent_internal_tx
    previous_trace = self.ethereum_tracing_client.tracing.get_previous_trace(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 993, in get_previous_trace
    traces = reversed(self.trace_transaction(tx_hash))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gnosis/eth/ethereum_client.py", line 1067, in trace_transaction
    return self.slow_w3.tracing.trace_transaction(tx_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 330, in request_blocking
    return self.formatted_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/web3/manager.py", line 279, in formatted_response
    raise MethodUnavailable(
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method trace_transaction does not exist/is not available'}
2024-08-14 01:48:00,996 MT::GET::api/v1/safes/<str:address>/creation/::46::500::/api/v1/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/creation/
```

CGW log:
```
{"build_number":"234a559","level":"error","message":{"chain_id":"530","client_ip":"172.30.187.89","detail":"An error occurred","method":"GET","origin":null,"path":"/v1/chains/530/safes/0x92d7986F80c3179561166D83ee2A2B3d0B35c7A8/transactions/history?timezone_offset=28800000&trusted=false","response_time_ms":70.46555100381374,"route":"/v1/chains/:chainId/safes/:safeAddress/transactions/history","safe_app_user_agent":null,"status_code":500},"request_id":"5818ab3b-b5cb-455d-a9b2-e3674d0e7a80","timestamp":"2024-08-14T01:48:00.998Z","version":"v1.53.0"}
```

**To Reproduce**
1. Setup using https://github.com/safe-global/safe-infrastructure/
2. Create safe wallet UI
3. Go to dashboard -> transaction history

**Expected behavior**
It should display the transaction history

**Environment (please complete the following information):**
 - Production
 - Chain: fxcore mainnet and testnet
 - Chrome
 - Version: latest on all components

**Additional context**
![image](https://github.com/user-attachments/assets/c6274884-fb16-450d-a011-898a5c4edbb2)

**Comment by lance-web3** [comment]
@moisses89 @Uxio0 can help please

**Comment by lance-web3** [comment]
Our RPC does not have trace namespace

Only debug namespace is available e.g. debug_traceTransaction

**Comment by moisses89** [comment]
Is the RPC supporting tracing? We recommend if the fees are not too expensive index by events instead tracing. Just unset the tracing node configuration.

**Comment by lance-web3** [comment]
unset the tracing node fixed the issue
