### ISSUE TITLE
`safes/<str:address>/all-transactions/` returns 500 error

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-transaction-service#975]
**Describe the bug**
The endpoint `api/v1/safes/<str:address>/all-transactions/` returns 500 error when cannot retrieve data of a collectible. 

**To Reproduce**
Taken from logs 

**Expected behavior**
Return the transactions without need the metadata of the token? 

**Additional context**
```
Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request    six.raise_from(e, None)  File "<string>", line 3, in raise_from  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send    resp = conn.urlopen(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen    retries = retries.increment(  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment    raise six.reraise(type(error), error, _stacktrace)  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise    raise value  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen    httplib_response = self._make_request(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout    raise ReadTimeoutError(urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='api.possessednfts.xyz', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 183, in _retrieve_metadata_from_uri    with requests.get(uri, timeout=10, stream=True) as response:  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get    return request("get", url, params=params, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request    return session.request(method=method, url=url, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request    resp = self.send(prep, **send_kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send    r = adapter.send(request, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send    raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPConnectionPool(host='api.possessednfts.xyz', port=80): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 248, in get_metadata
    return self._retrieve_metadata_from_uri(collectible.uri)
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 700, in wrapper
    v = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 156, in inner
    raise result
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 137, in inner
    result = func(*args, **kwargs)
  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 211, in _retrieve_metadata_from_uri
    raise MetadataRetrievalException(uri) from e
safe_transaction_service.history.services.collectibles_service.MetadataRetrievalException: http://api.possessednfts.xyz/ipfs/6
2022-07-19T17:18:26Z <Greenlet at 0x7fdfa2242440: <bound method CollectiblesService.get_metadata of <safe_transaction_service.history.services.collectibles_service.CollectiblesService object at 0x7fdfe95a4400>>(Collectible(token_name='Possessed', token_symbol=')> failed with MetadataRetrievalException

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request    six.raise_from(e, None)  File "<string>", line 3, in raise_from  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send    resp = conn.urlopen(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen    retries = retries.increment(  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment    raise six.reraise(type(error), error, _stacktrace)  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise    raise value  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen    httplib_response = self._make_request(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout    raise ReadTimeoutError(urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='api.adidas-originalsnft.xyz', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 183, in _retrieve_metadata_from_uri    with requests.get(uri, timeout=10, stream=True) as response:  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get    return request("get", url, params=params, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request    return session.request(method=method, url=url, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request    resp = self.send(prep, **send_kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send    r = adapter.send(request, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send    raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPConnectionPool(host='api.adidas-originalsnft.xyz', port=80): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 248, in get_metadata
    return self._retrieve_metadata_from_uri(collectible.uri)
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 700, in wrapper
    v = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 156, in inner
    raise result
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 137, in inner
    result = func(*args, **kwargs)
  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 211, in _retrieve_metadata_from_uri
    raise MetadataRetrievalException(uri) from e
safe_transaction_service.history.services.collectibles_service.MetadataRetrievalException: http://api.adidas-originalsnft.xyz/ipfs/5006
2022-07-19T17:18:26Z <Greenlet at 0x7fdfa2240940: <bound method CollectiblesService.get_metadata of <safe_transaction_service.history.services.collectibles_service.CollectiblesService object at 0x7fdfe95a4400>>(Collectible(token_name='Adidas', token_symbol='ADI)> failed with MetadataRetrievalException

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 449, in _make_request    six.raise_from(e, None)  File "<string>", line 3, in raise_from  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send    resp = conn.urlopen(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen    retries = retries.increment(  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment    raise six.reraise(type(error), error, _stacktrace)  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise    raise value  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen    httplib_response = self._make_request(  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 451, in _make_request    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout    raise ReadTimeoutError(urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='api.possessednfts.xyz', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 183, in _retrieve_metadata_from_uri    with requests.get(uri, timeout=10, stream=True) as response:  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get    return request("get", url, params=params, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request    return session.request(method=method, url=url, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request    resp = self.send(prep, **send_kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send    r = adapter.send(request, **kwargs)  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 578, in send    raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPConnectionPool(host='api.possessednfts.xyz', port=80): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 248, in get_metadata
    return self._retrieve_metadata_from_uri(collectible.uri)
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 700, in wrapper
    v = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 156, in inner
    raise result
  File "/usr/local/lib/python3.10/site-packages/cache_memoize/__init__.py", line 137, in inner
    result = func(*args, **kwargs)
  File "/app/safe_transaction_service/history/services/collectibles_service.py", line 211, in _retrieve_metadata_from_uri
    raise MetadataRetrievalException(uri) from e
safe_transaction_service.history.services.collectibles_service.MetadataRetrievalException: http://api.possessednfts.xyz/ipfs/6
2022-07-19T17:18:26Z <Greenlet at 0x7fdfa22432e0: <bound method CollectiblesService.get_metadata of <safe_transaction_service.history.services.collectibles_service.CollectiblesService object at 0x7fdfe95a4400>>(Collectible(token_name='Possessed', token_symbol=')> failed with MetadataRetrievalException

```

**Comment by Uxio0** [comment]
@moisses89 I'm quite sure that this error does not come from collectibles. and this is just a shared gevent coroutine, so the only way to fix this issue would be finding a url where this is reproducible

I see this only happened 5 times last week, all in the same day in an interval of a few hours and with different Safes, maybe something was off (for example, Redis), I would not time on this unless we see this happens again or we can reproduce

**Comment by moisses89** [comment]
Ok, I will check, I'm going to assign it to myself to keep updated if this happens again.

**Comment by moisses89** [comment]
I couldn't reproduce this issue.   
Anyway is still happen but is not directly associated with this endpoint and seems that it happens when some task can't get collectible metadata.

**Comment by Uxio0** [comment]
Then maybe we can close this as "not planned"
